# Generated by Django 3.2 on 2023-10-27 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccm', '0003_auto_20231026_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccm.child')),
            ],
        ),
    ]
