# Generated by Django 4.2.6 on 2023-10-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccm', '0005_remove_weeklycharge_tuition_fee_teacher_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='parent',
        ),
        migrations.AddField(
            model_name='child',
            name='parents',
            field=models.ManyToManyField(to='ccm.parent'),
        ),
    ]
