# Generated by Django 4.2.6 on 2023-10-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccm', '0006_remove_child_parent_child_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
