# Generated by Django 4.2.6 on 2023-10-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccm', '0008_alter_parent_email_alter_parent_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='children',
            field=models.ManyToManyField(to='ccm.child'),
        ),
    ]
