# Generated by Django 4.2.6 on 2023-10-29 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccm', '0009_classroom_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='children',
        ),
        migrations.AddField(
            model_name='child',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ccm.classroom'),
        ),
    ]
